services:
  _defaults:
    autowire: true

  Aznoqmous\ContaoMultilangBundle\EventListener\InitializeSystemListener:
    tags:
      - { name: contao.hook, hook: initializeSystem, priority: 0 }

  Aznoqmous\ContaoMultilangBundle\EventListener\InitializeMultilangConfigListener:
    tags:
      - { name: kernel.event_listener, event: multilang.initialize_config}

  Aznoqmous\ContaoMultilangBundle\EventListener\FrontendMultilangRedirectListener:
    tags:
      - { name: kernel.event_listener, event: multilang.frontend_redirect}
